name: Deploy the Github project update status monitor

env:
  GIT_URI:  ${{ secrets.GIT_URI }}

  GIT_USERNAME: ${{ secrets.GIT_USERNAME	}}
  GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}

  GITHUB_USERNAME: ${{ secrets.GIT_USERNAME	}}
  GITHUB_PASSWORD: ${{ secrets.GIT_PASSWORD }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0,30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Updates the remote profile page
        run: hub --version && ./run.sh


