name: Deploy the Github project update status monitor

env:
  PERSONAL_ACCESS_TOKEN:  ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  ARTIFACTORY_USERNAME:  ${{ secrets.ARTIFACTORY_USERNAME }}
  ARTIFACTORY_PASSWORD:  ${{ secrets.ARTIFACTORY_PASSWORD }}
  GUSM_DB_USERNAME:  ${{ secrets.GUSM_DB_USERNAME }}
  GUSM_DB_HOST:  ${{ secrets.GUSM_DB_HOST }}
  GUSM_DB_NAME:  ${{ secrets.GUSM_DB_NAME }}
  GUSM_DB_PASSWORD:  ${{ secrets.GUSM_DB_PASSWORD }}
 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0,30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Run the Github Update Status Monitor
        run: ./run.sh


